name: test

on:
  push: { branches: [master] }
  pull_request: { branches: [master] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - name: test
      run: go mod download && go test -v .
